# This is a basic workflow to help you get started with Actions

name: RUN-ATOM-CLI

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      cmd:
        description: "执行的命令, 不需要 yarn cli 前缀"
        required: true
        type: string
      wallet_json:
        description: "钱包文件"
        required: true
        type: string
      fullnode:
        description: "节点地址"
        required: true
        default: "https://ep.nextdao.xyz"
        type: string
      times:
        description: "执行次数"
        required: true
        type: number
        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  mint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 20
  
      - name: mint
        run: |
          git clone https://github.com/atomicals/atomicals-js.git atomicals-js
          cd atomicals-js
          npm install -g yarn
          yarn install
          yarn run build

          export ELECTRUMX_PROXY_BASE_URL=${{ github.event.inputs.fullnode }}
          echo use electrumx_proxy: $ELECTRUMX_PROXY_BASE_URL
          echo work on: $(pwd)
          cat << EOF > wallet.json
          ${{ github.event.inputs.wallet_json }}
          EOF
          for times in $(seq 1 ${{ github.event.inputs.times }}); do
            echo "RUN: yarn cli ${{ github.event.inputs.cmd }} $times times."
            yarn cli ${{ github.event.inputs.cmd }}
          done

