# This is a basic workflow to help you get started with Actions

name: RUN-ATOM-CLI

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      cmd:
        description: "执行的命令"
        required: true
        type: string
      wallet_json:
        description: "钱包文件"
        required: true
        type: string
      fullnode:
        description: "节点地址"
        required: true
        default: "https://ep.nextdao.xyz"
        type: string
      times:
        description: "执行次数"
        required: true
        type: number
        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  mint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 20
  
      - name: install atom cli
        run: |
          git clone https://github.com/atomicals/atomicals-js.git
          cd atomicals-js
          npm install -g yarn
          yarn install
          yarn run build

      # Runs a set of commands using the runners shell
      - name: start mint
        run: |
          export ELECTRUMX_PROXY_BASE_URL=${{ github.event.inputs.fullnode }}
          echo use electrumx_proxy: $ELECTRUMX_PROXY_BASE_URL
          echo RUN: ${{ github.event.inputs.cmd }}
          echo '${{ github.event.inputs.wallet_json }}' > wallet.json
          echo ${{ github.event.inputs.times }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: wallet.json
          path: wallet.json
      
